image: docker:latest
services:
  - docker:dind

stages:
  - testing
  - build
  - deploy

playground-cypress-testing:
  except:
    - production
    - /^hot-fix-prod.*$/
  image: cypress/base:10
  stage: testing
  retry: 2
  before_script:
    - npm i
    - npm start &
  script:
    - npm install --save-dev cypress
    - $(npm bin)/cypress verify
    - $(npm bin)/cypress run --spec "cypress/integration/examples/cp_collect.spec.js,cypress/integration/examples/settings_page.spec.js"

playground-npm-build:
  only:
    - master
  image: node:10-alpine
  stage: build
  script:
    - npm i
    - npm run build-playground
  artifacts:
    paths:
      - build/*

playground-deploy-to-s3:
  only:
    - master
  image: ubuntu:18.04
  stage: deploy
  script:
    - apt-get update && apt-get -y install python3 python3-pip
    - pip3 --no-cache-dir install --upgrade awscli
    - export AWS_ACCESS_KEY_ID=$CI_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CI_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=eu-west-1
    - aws s3 cp build/ s3://playground-app.bravofy.com/ --recursive
    - aws s3 cp build/index.js s3://playground-app.bravofy.com/index.js --cache-control 'no-cache'
    - aws s3 cp build/index.html s3://playground-app.bravofy.com/index.html --cache-control 'no-cache'

prod-cypress-testing:
  only:
    - production
    - /^hot-fix-prod.*$/
  image: cypress/base:10
  stage: testing
  retry: 2
  before_script:
    - npm i
    - npm run start-for-production &
  script:
    - npm install --save-dev cypress
    - $(npm bin)/cypress verify
    - $(npm bin)/cypress run

prod-npm-build:
  only:
    - production
  image: node:10-alpine
  stage: build
  script:
    - npm i
    - npm run build-production
  artifacts:
    paths:
      - build/*

prod-deploy-to-s3:
  only:
    - production
  image: ubuntu:18.04
  stage: deploy
  script:
    - apt-get update && apt-get -y install python3 python3-pip
    - pip3 --no-cache-dir install --upgrade awscli
    - export AWS_ACCESS_KEY_ID=$CI_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CI_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=eu-west-1
    - aws s3 cp build/ s3://app.bravofy.com/ --recursive
    - aws s3 cp build/index.js s3://app.bravofy.com/index.js --cache-control 'no-cache'
    - aws s3 cp build/index.html s3://app.bravofy.com/index.html --cache-control 'no-cache'

