image: docker:latest
services:
- docker:dind

stages:
- build
- deploy

npm-build:
  only:
  - master
  image: node:10
  stage: build
  script:
  - npm i
  - npm run build
  artifacts:
    paths:
    - build/*

deploy-to-s3:
  only:
  - master
  image: ubuntu:18.04
  stage: deploy
  script:
  - apt-get update && apt-get -y install python3 python3-pip
  - pip3 --no-cache-dir install --upgrade awscli
  - export AWS_ACCESS_KEY_ID=AKIAJR5HUU2B75ROLR6Q
  - export AWS_SECRET_ACCESS_KEY=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
  - export AWS_DEFAULT_REGION=eu-west-1
  - aws s3 cp build/ s3://marketing.iungo.network/ --recursive

